type ExportFormat = "pdf" | "word" | "excel";

interface ExportOptions {
  element: HTMLElement | null;
  format: ExportFormat;
  title: string;
  filename: string;
}

function collectTables(element: HTMLElement) {
  return Array.from(element.querySelectorAll("table")).map((table, index) => {
    const rows = Array.from(table.querySelectorAll("tr")).map((row) =>
      Array.from(row.querySelectorAll("th, td")).map(
        (cell) => cell.textContent?.trim() || ""
      )
    );

    return {
      name: `Table ${index + 1}`,
      headers: rows[0] || [],
      rows: rows.slice(1),
    };
  });
}

function buildHtml(element: HTMLElement, title: string) {
  const clone = element.cloneNode(true) as HTMLElement;

  clone
    .querySelectorAll("[data-no-export], .no-export")
    .forEach((node) => node.remove());

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
@page {
  size: Letter;
  margin: 0.7in;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: #ffffff;
  color: #17202a;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 11pt;
  line-height: 1.55;
}

.document {
  max-width: 7in;
  margin: 0 auto;
}

.header {
  border-bottom: 2px solid #17202a;
  padding-bottom: 14px;
  margin-bottom: 24px;
}

.brand {
  font-size: 9pt;
  font-weight: 700;
  letter-spacing: .14em;
  text-transform: uppercase;
  color: #52606d;
  margin-bottom: 6px;
}

.title {
  font-size: 24pt;
  line-height: 1.15;
  font-weight: 700;
  color: #111827;
  margin: 0;
}

.content {
  width: 100%;
}

h1 {
  font-size: 20pt;
  margin: 24px 0 10px;
  page-break-after: avoid;
}

h2 {
  font-size: 16pt;
  margin: 22px 0 9px;
  page-break-after: avoid;
}

h3 {
  font-size: 13pt;
  margin: 18px 0 7px;
  page-break-after: avoid;
}

p {
  margin: 0 0 10px;
}

ul, ol {
  margin: 7px 0 13px 22px;
}

li {
  margin: 4px 0;
}

strong {
  font-weight: 700;
  color: #111827;
}

code {
  font-family: Consolas, "Liberation Mono", monospace;
  font-size: 9pt;
  background: #f3f4f6;
  padding: 2px 5px;
  border-radius: 3px;
}

pre {
  font-family: Consolas, "Liberation Mono", monospace;
  font-size: 9pt;
  line-height: 1.45;
  background: #f3f4f6;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  padding: 12px;
  white-space: pre-wrap;
  overflow-wrap: anywhere;
  page-break-inside: avoid;
}

blockquote {
  border-left: 3px solid #64748b;
  margin: 14px 0;
  padding: 4px 0 4px 14px;
  color: #4b5563;
}

hr {
  border: 0;
  border-top: 1px solid #d1d5db;
  margin: 20px 0;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin: 16px 0 20px;
  font-size: 9.5pt;
  page-break-inside: auto;
}

thead {
  display: table-header-group;
}

th {
  background: #eef1f4;
  color: #111827;
  font-weight: 700;
  text-align: left;
  border: 1px solid #cbd5e1;
  padding: 7px 8px;
}

td {
  border: 1px solid #d1d5db;
  padding: 7px 8px;
  vertical-align: top;
}

tr {
  page-break-inside: avoid;
}

.footer {
  margin-top: 28px;
  padding-top: 10px;
  border-top: 1px solid #d1d5db;
  font-size: 8.5pt;
  color: #6b7280;
}
</style>
</head>
<body>
<div class="document">
  <div class="header">
    <div class="brand">Signal87 AI</div>
    <h1 class="title">${title}</h1>
  </div>
  <div class="content">
    ${clone.innerHTML}
  </div>
  <div class="footer">
    Generated by Signal87 AI
  </div>
</div>
</body>
</html>`;
}

export async function exportResult({
  element,
  format,
  title,
  filename,
}: ExportOptions): Promise<void> {
  if (!element) {
    throw new Error("Nothing to export.");
  }

  const html = buildHtml(element, title);
  const tables = collectTables(element);

  const response = await fetch("/api/export-document", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      format,
      html,
      tables,
      title,
      filename,
    }),
  });

  if (!response.ok) {
    throw new Error(`Export failed: ${response.status}`);
  }

  const blob = await response.blob();

  const extension =
    format === "pdf"
      ? "pdf"
      : format === "word"
        ? "docx"
        : "xlsx";

  const safeFilename =
    filename.replace(/[^a-zA-Z0-9-_]/g, "-") || "signal87-export";

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `${safeFilename}.${extension}`;
  document.body.appendChild(link);
  link.click();
  link.remove();

  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
