type ExportFormat = "word" | "excel";

interface ExportOptions {
  element: HTMLElement | null;
  format: ExportFormat;
  title: string;
  filename: string;
}

interface ExportTable {
  name: string;
  headers: string[];
  rows: string[][];
}

function safeFilename(filename: string) {
  return filename.replace(/[^a-zA-Z0-9-_]/g, "-") || "signal87-export";
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function cleanText(value: string | null | undefined) {
  return (value || "").replace(/\s+/g, " ").trim();
}

function collectTables(element: HTMLElement): ExportTable[] {
  return Array.from(element.querySelectorAll("table")).map((table, index) => {
    const rows = Array.from(table.querySelectorAll("tr")).map((row) =>
      Array.from(row.querySelectorAll("th, td")).map((cell) => cleanText(cell.textContent))
    );
    return { name: `Table ${index + 1}`, headers: rows[0] || [], rows: rows.slice(1) };
  });
}

function collectAnswerRows(element: HTMLElement) {
  const semanticNodes = Array.from(element.querySelectorAll("h1, h2, h3, h4, p, li, pre, blockquote"));
  if (semanticNodes.length === 0) return [["Answer", cleanText(element.textContent)]];
  return semanticNodes.map((node) => {
    const tag = node.tagName.toLowerCase();
    const kind = tag.startsWith("h") ? "Section" : tag === "li" ? "List item" : tag === "pre" ? "Code" : tag === "blockquote" ? "Quote" : "Answer";
    return [kind, cleanText(node.textContent)];
  }).filter((row) => row[1]);
}

async function exportWord(element: HTMLElement, title: string, filename: string) {
  const { Document, HeadingLevel, Packer, Paragraph, Table, TableCell, TableRow, TextRun, WidthType } = await import("docx");
  const children: Array<InstanceType<typeof Paragraph> | InstanceType<typeof Table>> = [
    new Paragraph({ text: "SIGNAL87 AI", style: "Subtitle" }),
    new Paragraph({ text: title, heading: HeadingLevel.TITLE, spacing: { after: 360 } }),
  ];

  const appendNode = (node: Element) => {
    if (node.matches("[data-no-export], .no-export, button")) return;
    const tag = node.tagName.toLowerCase();
    const text = cleanText(node.textContent);
    if (!text) return;

    if (/^h[1-4]$/.test(tag)) {
      const heading = tag === "h1" ? HeadingLevel.HEADING_1 : tag === "h2" ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3;
      children.push(new Paragraph({ text, heading, spacing: { before: 260, after: 110 } }));
      return;
    }
    if (tag === "p" || tag === "blockquote" || tag === "pre") {
      children.push(new Paragraph({ children: [new TextRun({ text, italics: tag === "blockquote", font: tag === "pre" ? "Courier New" : undefined })], spacing: { after: 150 } }));
      return;
    }
    if (tag === "li") {
      children.push(new Paragraph({ text, bullet: { level: 0 }, spacing: { after: 70 } }));
      return;
    }
    if (tag === "table") {
      const rows = Array.from(node.querySelectorAll("tr")).map((row) => new TableRow({
        children: Array.from(row.querySelectorAll(":scope > th, :scope > td")).map((cell) =>
          new TableCell({ children: [new Paragraph({ text: cleanText(cell.textContent) })] })
        ),
      }));
      if (rows.length > 0) children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }));
      return;
    }
    Array.from(node.children).forEach(appendNode);
  };

  Array.from(element.children).forEach(appendNode);
  if (children.length === 2) children.push(new Paragraph({ text: cleanText(element.textContent) }));
  children.push(new Paragraph({ text: "Generated by Signal87 AI", style: "Caption", spacing: { before: 360 } }));
  const documentFile = new Document({ sections: [{ properties: {}, children }] });
  const blob = await Packer.toBlob(documentFile);
  downloadBlob(blob, `${safeFilename(filename)}.docx`);
}

async function exportExcel(element: HTMLElement, title: string, filename: string) {
  const ExcelJS = (await import("exceljs")).default;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Signal87 AI";
  workbook.created = new Date();
  workbook.subject = title;
  const tables = collectTables(element);

  if (tables.length > 0) {
    tables.forEach((table, index) => {
      const worksheet = workbook.addWorksheet(`Table ${index + 1}`);
      worksheet.addRow(table.headers);
      table.rows.forEach((row) => worksheet.addRow(row));
      worksheet.views = [{ state: "frozen", ySplit: 1 }];
      worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
      worksheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF173F3F" } };
      worksheet.columns.forEach((column) => {
        const lengths = (column.values || []).map((value) => String(value || "").length + 2);
        column.width = Math.min(48, Math.max(14, ...lengths));
      });
      worksheet.autoFilter = { from: { row: 1, column: 1 }, to: { row: Math.max(1, worksheet.rowCount), column: Math.max(1, table.headers.length) } };
    });
  } else {
    const worksheet = workbook.addWorksheet("Answer");
    worksheet.addRow(["Signal87 AI Export", title]);
    worksheet.addRow(["Content type", "Content"]);
    collectAnswerRows(element).forEach((row) => worksheet.addRow(row));
    worksheet.getRow(1).font = { bold: true, size: 14, color: { argb: "FFFFFFFF" } };
    worksheet.getRow(1).fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF173F3F" } };
    worksheet.getRow(2).font = { bold: true };
    worksheet.getColumn(1).width = 18;
    worksheet.getColumn(2).width = 90;
    worksheet.getColumn(2).alignment = { wrapText: true, vertical: "top" };
    worksheet.views = [{ state: "frozen", ySplit: 2 }];
  }

  const data = await workbook.xlsx.writeBuffer();
  const blob = new Blob([data as BlobPart], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  downloadBlob(blob, `${safeFilename(filename)}.xlsx`);
}

export async function exportResult({ element, format, title, filename }: ExportOptions): Promise<void> {
  if (!element) throw new Error("Nothing to export.");
  if (format === "word") return exportWord(element, title, filename);
  return exportExcel(element, title, filename);
}
