/**
 * Mirrors the Chambers token block out of src/index.css into
 * public/chambers.css.
 *
 * The three static pages served at /privacy, /terms and /team are standalone
 * HTML with their own <style> — they never go through Vite, so they cannot
 * import the app's stylesheet. Rather than hand-copying the palette into three
 * files and letting it drift, they all link this one generated file.
 *
 * src/index.css stays the single source of truth. Run `npm run tokens` after
 * changing the palette; the theme guard fails the build if this file is stale.
 */
import { readFileSync, writeFileSync } from 'fs';

const SRC = new URL('../src/index.css', import.meta.url);
const OUT = new URL('../public/chambers.css', import.meta.url);

const css = readFileSync(SRC, 'utf8');

// The palette block is the :root that defines --bg. The other :root blocks in
// that file carry the dock height and the field treatment, which the static
// pages have no use for.
const match = css.match(/:root\{[^}]*--bg:[^}]*\}/s);
if (!match) throw new Error('could not find the Chambers :root block in src/index.css');

const banner = `/* GENERATED by npm run tokens — do not edit.

   The Chambers palette, mirrored out of src/index.css so the standalone pages
   at /privacy, /terms and /team can use the same tokens as the app. Edit the
   palette there, then re-run the generator. */

`;

writeFileSync(OUT, banner + match[0] + '\n');
console.log(`public/chambers.css written (${match[0].length} bytes of tokens)`);
