import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
import HTMLtoDOCX from 'html-to-docx';
import ExcelJS from 'exceljs';

function sanitizeFilename(name = 'Signal87-Export'): string {
  return name.replace(/[^\w\s.-]/g, '').replace(/\s+/g, '-').substring(0, 100) || 'Signal87-Export';
}

function smartExcelValue(value: unknown): unknown {
  if (value === null || value === undefined) return '';
  if (typeof value === 'number') return value;
  const str = String(value).trim();
  if (!str) return '';
  if (/^-?[\d,.]+%$/.test(str)) return Number(str.replace(/,/g, '').replace('%', '')) / 100;
  if (/^-?\$[\d,.]+$/.test(str)) return Number(str.replace(/[$,]/g, ''));
  if (/^-?[\d,.]+$/.test(str)) {
    const n = Number(str.replace(/,/g, ''));
    if (!Number.isNaN(n)) return n;
  }
  return str;
}

export function exportHtmlShell(body: string, title: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>@page{size:Letter;margin:.55in}html,body{background:#fff!important}body{margin:0;padding:0;-webkit-print-color-adjust:exact;print-color-adjust:exact}table{width:100%;border-collapse:collapse;break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}img,svg{max-width:100%}h1,h2,h3,h4{break-after:avoid}.no-export,[data-no-export]{display:none!important}</style></head><body>${body}</body></html>`;
}

export async function renderPdf(html: string): Promise<Buffer> {
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: { width: 1440, height: 1000, deviceScaleFactor: 2 },
    executablePath: await chromium.executablePath(),
    headless: true
  });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0', timeout: 60000 });
    await page.emulateMediaType('screen');
    const pdf = await page.pdf({
      format: 'Letter',
      printBackground: true,
      preferCSSPageSize: true,
      margin: { top: '.55in', right: '.55in', bottom: '.65in', left: '.55in' },
      displayHeaderFooter: true,
      headerTemplate: '<div></div>',
      footerTemplate: '<div style="width:100%;padding:0 .55in;display:flex;justify-content:space-between;font:8px Arial;color:#94a3b8"><span>Generated by Signal87 AI</span><span><span class="pageNumber"></span> / <span class="totalPages"></span></span></div>'
    });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}

export async function renderWord(html: string): Promise<Buffer> {
  const result = await HTMLtoDOCX(html, null, {
    title: 'Signal87 AI Report',
    creator: 'Signal87 AI',
    description: 'Generated by Signal87 AI',
    font: 'Arial',
    fontSize: 22,
    footer: true,
    pageNumber: true,
    table: { row: { cantSplit: true } },
    margins: { top: 720, right: 720, bottom: 720, left: 720 }
  });
  return Buffer.from(result);
}

export async function renderExcel(tables: Array<{ name?: string; headers?: string[]; rows?: unknown[][] }>, title: string): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Signal87 AI';
  workbook.company = 'Signal87 AI';
  workbook.created = new Date();
  const sourceTables = tables.length ? tables : [{ name: 'Export', headers: ['Result'], rows: [['No tabular data supplied']] }];

  sourceTables.forEach((table, index) => {
    const sheetName = (table.name || `Analysis ${index + 1}`).replace(/[\\/*?:\[\]]/g, '').substring(0, 31) || `Sheet${index + 1}`;
    const ws = workbook.addWorksheet(sheetName, { views: [{ state: 'frozen', ySplit: 1 }] });
    const headers = table.headers || [];
    if (index === 0 && title) {
      ws.addRow([title]);
      ws.mergeCells(1, 1, 1, Math.max(headers.length, 1));
      ws.getCell(1, 1).font = { bold: true, size: 18 };
      ws.getRow(1).height = 30;
      ws.addRow([]);
    }
    const headerRowNumber = index === 0 && title ? 3 : 1;
    if (headers.length) {
      const row = ws.getRow(headerRowNumber);
      headers.forEach((header, i) => {
        const cell = row.getCell(i + 1);
        cell.value = header;
        cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF111827' } };
        cell.alignment = { vertical: 'middle', wrapText: true };
      });
      row.height = 28;
      ws.autoFilter = { from: { row: headerRowNumber, column: 1 }, to: { row: headerRowNumber, column: headers.length } };
    }
    (table.rows || []).forEach((dataRow, ri) => {
      const row = ws.getRow(headerRowNumber + 1 + ri);
      dataRow.forEach((value, ci) => {
        const cell = row.getCell(ci + 1);
        const converted = smartExcelValue(value);
        cell.value = converted as any;
        cell.alignment = { vertical: 'top', wrapText: true };
        if (typeof value === 'string' && value.trim().endsWith('%') && typeof converted === 'number') cell.numFmt = '0.00%';
        if (typeof value === 'string' && value.trim().startsWith('$') && typeof converted === 'number') cell.numFmt = '$#,##0.00;[Red]-$#,##0.00';
      });
    });
    ws.columns.forEach(column => {
      let max = 12;
      column.eachCell({ includeEmpty: true }, cell => { max = Math.max(max, Math.min(String(cell.value ?? '').length + 3, 45)); });
      column.width = max;
    });
    ws.pageSetup = { orientation: headers.length > 6 ? 'landscape' : 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 };
  });
  return Buffer.from(await workbook.xlsx.writeBuffer());
}

export { sanitizeFilename };
