import { onRequest } from 'firebase-functions/v2/https';
import chromium from '@sparticuz/chromium';
import puppeteer from 'puppeteer-core';
import HTMLtoDOCX from 'html-to-docx';
import ExcelJS from 'exceljs';

function safeName(name = 'Signal87-Export') {
  return name.replace(/[^\w\s.-]/g, '').replace(/\s+/g, '-').slice(0, 100) || 'Signal87-Export';
}

function shell(body: string, title: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>@page{size:Letter;margin:.55in}body{margin:0;background:#fff;color:#111827;font-family:Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}table{width:100%;border-collapse:collapse;break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}img,svg{max-width:100%}h1,h2,h3,h4{break-after:avoid}.no-export,[data-no-export]{display:none!important}</style></head><body>${body}</body></html>`;
}

async function makePdf(html: string) {
  const browser = await puppeteer.launch({ args: chromium.args, executablePath: await chromium.executablePath(), headless: true, defaultViewport: { width: 1440, height: 1000, deviceScaleFactor: 2 } });
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0', timeout: 60000 });
    await page.emulateMediaType('screen');
    return Buffer.from(await page.pdf({ format: 'Letter', printBackground: true, preferCSSPageSize: true, margin: { top: '.55in', right: '.55in', bottom: '.65in', left: '.55in' }, displayHeaderFooter: true, headerTemplate: '<div></div>', footerTemplate: '<div style="width:100%;padding:0 .55in;display:flex;justify-content:space-between;font:8px Arial;color:#94a3b8"><span>Generated by Signal87 AI</span><span><span class="pageNumber"></span> / <span class="totalPages"></span></span></div>' }));
  } finally { await browser.close(); }
}

async function makeWord(html: string) {
  const doc = await HTMLtoDOCX(html, null, { title: 'Signal87 AI Report', creator: 'Signal87 AI', description: 'Generated by Signal87 AI', font: 'Arial', fontSize: 22, footer: true, pageNumber: true, table: { row: { cantSplit: true } }, margins: { top: 720, right: 720, bottom: 720, left: 720 } });
  return Buffer.from(doc);
}

function excelValue(value: unknown) {
  if (value === null || value === undefined) return '';
  if (typeof value === 'number') return value;
  const s = String(value).trim();
  if (/^-?[\d,.]+%$/.test(s)) return Number(s.replace(/,/g, '').replace('%', '')) / 100;
  if (/^-?\$[\d,.]+$/.test(s)) return Number(s.replace(/[$,]/g, ''));
  if (/^-?[\d,.]+$/.test(s)) return Number(s.replace(/,/g, ''));
  return s;
}

async function makeExcel(tables: any[], title: string) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Signal87 AI'; wb.company = 'Signal87 AI'; wb.created = new Date();
  const source = tables.length ? tables : [{ name: 'Export', headers: ['Result'], rows: [['No tabular data supplied']] }];
  source.forEach((table: any, index: number) => {
    const name = (table.name || `Analysis ${index + 1}`).replace(/[\\/*?:\[\]]/g, '').slice(0, 31) || `Sheet${index + 1}`;
    const ws = wb.addWorksheet(name, { views: [{ state: 'frozen', ySplit: 1 }] });
    const headers = Array.isArray(table.headers) ? table.headers : [];
    if (index === 0 && title) { ws.addRow([title]); ws.mergeCells(1, 1, 1, Math.max(headers.length, 1)); ws.getCell(1, 1).font = { bold: true, size: 18 }; ws.addRow([]); }
    const headerRow = index === 0 && title ? 3 : 1;
    if (headers.length) {
      const row = ws.getRow(headerRow);
      headers.forEach((h: string, i: number) => { const c = row.getCell(i + 1); c.value = h; c.font = { bold: true, color: { argb: 'FFFFFFFF' } }; c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF111827' } }; c.alignment = { vertical: 'middle', wrapText: true }; });
      ws.autoFilter = { from: { row: headerRow, column: 1 }, to: { row: headerRow, column: headers.length } };
    }
    (Array.isArray(table.rows) ? table.rows : []).forEach((dataRow: unknown[], ri: number) => dataRow.forEach((v, ci) => { const c = ws.getRow(headerRow + 1 + ri).getCell(ci + 1); const x = excelValue(v); c.value = x as any; c.alignment = { vertical: 'top', wrapText: true }; if (typeof v === 'string' && v.trim().endsWith('%') && typeof x === 'number') c.numFmt = '0.00%'; if (typeof v === 'string' && v.trim().startsWith('$') && typeof x === 'number') c.numFmt = '$#,##0.00;[Red]-$#,##0.00'; }));
    ws.columns.forEach(col => { let max = 12; col.eachCell({ includeEmpty: true }, c => { max = Math.max(max, Math.min(String(c.value ?? '').length + 3, 45)); }); col.width = max; });
    ws.pageSetup = { orientation: headers.length > 6 ? 'landscape' : 'portrait', fitToPage: true, fitToWidth: 1, fitToHeight: 0 };
  });
  return Buffer.from(await wb.xlsx.writeBuffer());
}

export const exportDocument = onRequest({ region: 'us-east1', timeoutSeconds: 120, memory: '2GiB', cors: true }, async (req, res) => {
  if (req.method !== 'POST') { res.setHeader('Allow', 'POST'); res.status(405).json({ error: 'Method Not Allowed' }); return; }
  try {
    const { format, html, tables = [], title = 'Signal87 AI Report', filename = 'Signal87-Report' } = req.body || {};
    if (!format) { res.status(400).json({ error: 'format is required' }); return; }
    const name = safeName(filename);
    if ((format === 'pdf' || format === 'word' || format === 'docx') && typeof html !== 'string') { res.status(400).json({ error: 'html is required' }); return; }
    if (format === 'pdf') { res.setHeader('Content-Type', 'application/pdf'); res.setHeader('Content-Disposition', `attachment; filename="${name}.pdf"`); res.send(await makePdf(shell(html, title))); return; }
    if (format === 'word' || format === 'docx') { res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'); res.setHeader('Content-Disposition', `attachment; filename="${name}.docx"`); res.send(await makeWord(shell(html, title))); return; }
    if (format === 'excel' || format === 'xlsx') { res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'); res.setHeader('Content-Disposition', `attachment; filename="${name}.xlsx"`); res.send(await makeExcel(Array.isArray(tables) ? tables : [], title)); return; }
    res.status(400).json({ error: `Unsupported export format: ${format}` });
  } catch (error: any) { console.error('Signal87 export error:', error); res.status(500).json({ error: 'Export generation failed', details: error?.message || String(error) }); }
});
